#pragma once

// Event types
enum {
    EV_KEY = 1,
    EV_BTN = 2,
    EV_REL = 3,
};

// Keyboard
enum {
    KEY_ESC        = 1,
    KEY_F1         = 2,
    KEY_F2         = 3,
    KEY_F3         = 4,
    KEY_F4         = 5,
    KEY_F5         = 6,
    KEY_F6         = 7,
    KEY_F7         = 8,
    KEY_F8         = 9,
    KEY_F9         = 10,
    KEY_F10        = 11,
    KEY_F11        = 12,
    KEY_F12        = 13,
    KEY_GRAVE      = 14,
    KEY_1          = 15,
    KEY_2          = 16,
    KEY_3          = 17,
    KEY_4          = 18,
    KEY_5          = 19,
    KEY_6          = 20,
    KEY_7          = 21,
    KEY_8          = 22,
    KEY_9          = 23,
    KEY_0          = 24,
    KEY_MINUS      = 25,
    KEY_EQUAL      = 26,
    KEY_BACKSPACE  = 27,
    KEY_TAB        = 28,
    KEY_Q          = 29,
    KEY_W          = 30,
    KEY_E          = 31,
    KEY_R          = 32,
    KEY_T          = 33,
    KEY_Y          = 34,
    KEY_U          = 35,
    KEY_I          = 36,
    KEY_O          = 37,
    KEY_P          = 38,
    KEY_LEFTBRACE  = 39,
    KEY_RIGHTBRACE = 40,
    KEY_BACKSLASH  = 41,
    KEY_CAPSLOCK   = 42,
    KEY_A          = 43,
    KEY_S          = 44,
    KEY_D          = 45,
    KEY_F          = 46,
    KEY_G          = 47,
    KEY_H          = 48,
    KEY_J          = 49,
    KEY_K          = 50,
    KEY_L          = 51,
    KEY_SEMICOLON  = 52,
    KEY_APOSTROPHE = 53,
    KEY_ENTER      = 54,
    KEY_LEFTSHIFT  = 55,
    KEY_Z          = 56,
    KEY_X          = 57,
    KEY_C          = 58,
    KEY_V          = 59,
    KEY_B          = 60,
    KEY_N          = 61,
    KEY_M          = 62,
    KEY_COMMA      = 63,
    KEY_DOT        = 64,
    KEY_SLASH      = 65,
    KEY_RIGHTSHIFT = 66,
    KEY_LEFTCTRL   = 67,
    KEY_LEFTMETA   = 68,
    KEY_LEFTALT    = 69,
    KEY_SPACE      = 70,
    KEY_RIGHTALT   = 71,
    KEY_RIGHTMETA  = 72,
    KEY_RIGHTCTRL  = 73,
    KEY_SYSRQ      = 74,
    KEY_SCROLLLOCK = 75,
    KEY_PAUSE      = 76,
    KEY_INSERT     = 77,
    KEY_HOME       = 78,
    KEY_PAGEUP     = 79,
    KEY_DELETE     = 80,
    KEY_END        = 81,
    KEY_PAGEDOWN   = 82,
    KEY_UP         = 83,
    KEY_LEFT       = 84,
    KEY_DOWN       = 85,
    KEY_RIGHT      = 86,
    KEY_NUMLOCK    = 87,
    KEY_KPSLASH    = 88,
    KEY_KPASTERISK = 89,
    KEY_KPPLUS     = 90,
    KEY_KPMINUS    = 91,
    KEY_KPDOT      = 92,
    KEY_KPENTER    = 93,
    KEY_KP0        = 94,
    KEY_KP1        = 95,
    KEY_KP2        = 96,
    KEY_KP3        = 97,
    KEY_KP4        = 98,
    KEY_KP5        = 99,
    KEY_KP6        = 100,
    KEY_KP7        = 101,
    KEY_KP8        = 102,
    KEY_KP9        = 103,
    KEY_102ND      = 104,
    KEY_COMPOSE    = 105,
};

// Mouse buttons
enum {
    BTN_MOUSE  = 0x100,
    BTN_LEFT   = 0x101,
    BTN_RIGHT  = 0x102,
    BTN_MIDDLE = 0x103,
};

// Relative movements
enum {
    REL_X = 1,
    REL_Y = 2,
    REL_Z = 3,
};
